semi: false
tabWidth: 2
useTabs: false
printWidth: 100
singleQuote: true
trailingComma: es5
bracketSpacing: true
proseWrap: preserve
overrides:
  - files:
      - '*.js'
      - '*.jsx'
      - '*.ts'
      - '*.tsx'
    options:
      parser: typescript
